spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
      - id:  Reception-Microservice
        uri: http://localhost:8083/**
        predicates:
        - Path=/receptionist/**
      - id: Owner-Microservice
        uri: http://localhost:8081/**
        predicates:
        - Path=/owner/**
      - id: Manager-Microservice
        uri: http://localhost:8082/**
        predicates:
        - Path=/manager/**
     
        
   
    